"""Selection hit testing, outlines, handles, and rotation policy."""

from .active_tool import ActiveToolReference
from .hit import (
    AtomHitCandidate,
    BondHitCandidate,
    SelectionHitRequest,
    SelectionRect,
    SelectionSnapshot,
    StructureHit,
    build_selection_snapshot,
    choose_preferred_structure_hit,
    nearest_ring_atom_id,
    padded_rect_contains_point,
    selected_atom_ids_with_bond_endpoints,
    selection_hit_matches,
    structure_hit_is_selected,
)
from .press import SelectionPressContext, SelectionPressDecision, plan_selection_press
from .rotation import rotated_atom_positions
from .rotation_geometry import (
    Coords3D,
    axis_rotated_coords,
    center_for_coords_3d,
    dominant_axis_angle_from_drag,
    flatten_coords_to_plane,
    fragment_plane_normal_for,
    normalize_3d,
    project_point_3d,
    rigid_rotated_coords,
    rigid_rotation_angles_from_drag,
    rotate_point_around_axis,
    translate_projected_point_3d,
    unproject_point_3d,
)

__all__ = [
    "ActiveToolReference",
    "AtomHitCandidate",
    "BondHitCandidate",
    "Coords3D",
    "SelectionHitRequest",
    "SelectionPressContext",
    "SelectionPressDecision",
    "SelectionRect",
    "SelectionSnapshot",
    "StructureHit",
    "axis_rotated_coords",
    "build_selection_snapshot",
    "center_for_coords_3d",
    "choose_preferred_structure_hit",
    "dominant_axis_angle_from_drag",
    "flatten_coords_to_plane",
    "fragment_plane_normal_for",
    "nearest_ring_atom_id",
    "normalize_3d",
    "padded_rect_contains_point",
    "plan_selection_press",
    "project_point_3d",
    "rigid_rotated_coords",
    "rigid_rotation_angles_from_drag",
    "rotate_point_around_axis",
    "rotated_atom_positions",
    "selected_atom_ids_with_bond_endpoints",
    "selection_hit_matches",
    "structure_hit_is_selected",
    "translate_projected_point_3d",
    "unproject_point_3d",
]
