"""Selection hit testing, outlines, handles, and rotation policy."""

from .active_tool import ActiveToolReference
from .center import bounding_box_center_for_atoms, center_for_atoms
from .handles import (
    clamp_curved_midpoint,
    clear_handle_items,
    control_from_midpoint,
    create_handle_item,
    curved_midpoint,
    default_curved_control,
    orbital_handle_positions,
    orbital_rotation_angle,
    orbital_scale_factor,
    resized_shape_rect,
    shape_resize_handle_positions,
)
from .hit import (
    AtomHitCandidate,
    BondHitCandidate,
    SelectionHitRequest,
    SelectionRect,
    SelectionSnapshot,
    StructureHit,
    build_selection_snapshot,
    choose_preferred_structure_hit,
    nearest_ring_atom_id,
    padded_rect_contains_point,
    selection_hit_matches,
    structure_hit_is_selected,
)
from .outline import (
    ARROW_OBJECT_KINDS,
    LineStrokePathBuilder,
    PenWidthGetter,
    selection_line_stroke_path,
    selection_path_for_bond_item,
    selection_path_for_object_item,
)
from .press import SelectionPressContext, SelectionPressDecision, plan_selection_press
from .rotation import rotated_atom_positions, selected_rotation_atom_ids
from .rotation_geometry import (
    ROTATION_DRAG_SENSITIVITY,
    Coords3D,
    RotatePointAroundAxis,
    axis_rotated_coords,
    center_for_coords_3d,
    dominant_axis_angle_from_drag,
    flatten_coords_to_plane,
    fragment_plane_normal_for,
    normalize_3d,
    rigid_rotated_coords,
    rigid_rotation_angles_from_drag,
    rotate_point_around_axis,
)

__all__ = [
    "ARROW_OBJECT_KINDS",
    "ROTATION_DRAG_SENSITIVITY",
    "ActiveToolReference",
    "AtomHitCandidate",
    "BondHitCandidate",
    "Coords3D",
    "LineStrokePathBuilder",
    "PenWidthGetter",
    "RotatePointAroundAxis",
    "SelectionHitRequest",
    "SelectionPressContext",
    "SelectionPressDecision",
    "SelectionRect",
    "SelectionSnapshot",
    "StructureHit",
    "axis_rotated_coords",
    "bounding_box_center_for_atoms",
    "build_selection_snapshot",
    "center_for_atoms",
    "center_for_coords_3d",
    "choose_preferred_structure_hit",
    "clamp_curved_midpoint",
    "clear_handle_items",
    "control_from_midpoint",
    "create_handle_item",
    "curved_midpoint",
    "default_curved_control",
    "dominant_axis_angle_from_drag",
    "flatten_coords_to_plane",
    "fragment_plane_normal_for",
    "nearest_ring_atom_id",
    "normalize_3d",
    "orbital_handle_positions",
    "orbital_rotation_angle",
    "orbital_scale_factor",
    "padded_rect_contains_point",
    "plan_selection_press",
    "resized_shape_rect",
    "rigid_rotated_coords",
    "rigid_rotation_angles_from_drag",
    "rotate_point_around_axis",
    "rotated_atom_positions",
    "selected_rotation_atom_ids",
    "selection_hit_matches",
    "selection_line_stroke_path",
    "selection_path_for_bond_item",
    "selection_path_for_object_item",
    "shape_resize_handle_positions",
    "structure_hit_is_selected",
]
