from __future__ import annotations

from collections.abc import Sequence
from typing import Any, cast

from PyQt6.QtCore import (
    QBuffer,
    QByteArray,
    QIODevice,
    QMarginsF,
    QRectF,
    QSize,
    QSizeF,
)
from PyQt6.QtGui import QPageSize, QPainter, QPdfWriter
from PyQt6.QtSvg import QSvgGenerator
from PyQt6.QtWidgets import QGraphicsItem, QGraphicsScene

from .painting import POINTS_PER_INCH, paint_scene_region
from .plan import ExportPlan
from .scope import exported_scene


def configure_svg_generator(
    generator: QSvgGenerator, plan: ExportPlan, title: str | None
) -> None:
    generator.setResolution(int(POINTS_PER_INCH))
    generator.setSize(QSize(max(1, round(plan.out_w_pt)), max(1, round(plan.out_h_pt))))
    generator.setViewBox(QRectF(0.0, 0.0, plan.out_w_pt, plan.out_h_pt))
    if title:
        generator.setTitle(title)
    generator.setDescription("Generated by Chemvas")


def configure_pdf_writer(
    writer: QPdfWriter, plan: ExportPlan, resolution: int, title: str | None
) -> None:
    writer.setResolution(int(resolution))
    writer.setPageSize(
        QPageSize(QSizeF(plan.out_w_pt, plan.out_h_pt), QPageSize.Unit.Point)
    )
    writer.setPageMargins(QMarginsF(0.0, 0.0, 0.0, 0.0))
    if title:
        writer.setTitle(title)


def export_svg_file(
    scene: QGraphicsScene,
    path: str,
    export_items: Sequence[QGraphicsItem],
    plan: ExportPlan,
    background: str,
    title: str | None,
) -> None:
    with exported_scene(scene, export_items):
        generator = QSvgGenerator()
        generator.setFileName(path)
        # Render at 72 dpi so 1 SVG user unit = 1 point => physical size = out_pt.
        configure_svg_generator(generator, plan, title)
        painter = QPainter()
        if not painter.begin(generator):
            raise ValueError("Failed to open SVG output for writing.")
        try:
            paint_scene_region(
                painter, scene, plan, plan.out_w_pt, plan.out_h_pt, background
            )
        finally:
            painter.end()


def render_svg_bytes(
    scene: QGraphicsScene,
    export_items: Sequence[QGraphicsItem],
    plan: ExportPlan,
    background: str,
    title: str | None,
) -> bytes:
    buffer_data = QByteArray()
    buffer = QBuffer(buffer_data)
    if not buffer.open(QIODevice.OpenModeFlag.WriteOnly):
        raise ValueError("Failed to open SVG clipboard buffer.")
    try:
        with exported_scene(scene, export_items):
            generator = QSvgGenerator()
            generator.setOutputDevice(buffer)
            configure_svg_generator(generator, plan, title)
            painter = QPainter()
            if not painter.begin(generator):
                raise ValueError("Failed to render SVG clipboard data.")
            try:
                paint_scene_region(
                    painter, scene, plan, plan.out_w_pt, plan.out_h_pt, background
                )
            finally:
                painter.end()
    finally:
        buffer.close()
    return bytes(cast(Any, buffer_data))


def export_pdf_file(
    scene: QGraphicsScene,
    path: str,
    export_items: Sequence[QGraphicsItem],
    plan: ExportPlan,
    resolution: int,
    background: str,
    title: str | None,
) -> None:
    with exported_scene(scene, export_items):
        writer = QPdfWriter(path)
        configure_pdf_writer(writer, plan, resolution, title)
        target_w = plan.out_w_pt / POINTS_PER_INCH * resolution
        target_h = plan.out_h_pt / POINTS_PER_INCH * resolution
        painter = QPainter()
        if not painter.begin(writer):
            raise ValueError("Failed to open PDF output for writing.")
        try:
            paint_scene_region(painter, scene, plan, target_w, target_h, background)
        finally:
            painter.end()


def render_pdf_bytes(
    scene: QGraphicsScene,
    export_items: Sequence[QGraphicsItem],
    plan: ExportPlan,
    background: str,
    title: str | None,
) -> bytes:
    buffer_data = QByteArray()
    buffer = QBuffer(buffer_data)
    if not buffer.open(QIODevice.OpenModeFlag.WriteOnly):
        raise ValueError("Failed to open PDF clipboard buffer.")
    try:
        with exported_scene(scene, export_items):
            writer = QPdfWriter(buffer)
            configure_pdf_writer(writer, plan, int(POINTS_PER_INCH), title)
            painter = QPainter()
            if not painter.begin(writer):
                raise ValueError("Failed to render PDF clipboard data.")
            try:
                paint_scene_region(
                    painter, scene, plan, plan.out_w_pt, plan.out_h_pt, background
                )
            finally:
                painter.end()
    finally:
        buffer.close()
    return bytes(cast(Any, buffer_data))


__all__ = [
    "configure_pdf_writer",
    "configure_svg_generator",
    "export_pdf_file",
    "export_svg_file",
    "render_pdf_bytes",
    "render_svg_bytes",
]
