"""Bond rendering policy and Qt geometry primitives."""

# The 3-D unit-vector helper belongs to the selection package's 3-D math, which
# owns Coords3D and the rotate-around-axis helpers. Rendering is otherwise 2-D
# and only re-exports it so bond geometry callers keep one import.
from chemvas.features.selection import normalize_3d

from .acs1996_style import ACS1996Style
from .bond_dotted import dotted_bond_dot_centers
from .bond_geometry import (
    DEFAULT_BOLD_OUT_LENGTH_SCALE,
    LineSegment,
    bold_double_strip_geometry,
    bold_out_scale,
    extend_segment,
    line_intersection,
    normal_away_from_parallel_segment,
    offset_segment,
    scale_segment,
    strip_corners,
    trim_segment,
)
from .bond_graphics import refresh_bond_graphics
from .bond_preview import plain_double_preview_segments
from .bond_stereo import (
    hash_segments_from_segment,
    trimmed_line_segment,
    wedge_triangle_from_segment,
)
from .bond_style import (
    BOLD_BOND_STYLES,
    BOLD_DOUBLE_STYLE_SEQUENCE,
    BOLD_DOUBLE_STYLES,
    BOLD_STYLE_CENTER,
    BOLD_STYLE_DEFAULT,
    BOLD_STYLE_OUTER,
    DOTTED_DOUBLE_STYLE_DEFAULT,
    DOTTED_DOUBLE_STYLE_OUTER,
    DOTTED_DOUBLE_STYLE_SEQUENCE,
    DOTTED_DOUBLE_STYLES,
    DOUBLE_STYLE_CENTER,
    DOUBLE_STYLE_DEFAULT,
    DOUBLE_STYLE_OUTER,
    DOUBLE_STYLE_SEQUENCE,
    PLAIN_DOUBLE_STYLES,
    STANDARD_BOND_STYLES,
    base_plain_double_style_for_dotted_variant,
    bold_double_style_for_position,
    bold_double_style_for_style,
    cycle_plain_bond_style,
    dotted_double_variant_for_style,
    double_position_for_style,
    is_bold_double_bond_style,
    is_dotted_double_bond_style,
    is_plain_double_bond_style,
    is_positionable_double_bond_style,
    normalized_bold_double_style,
    normalized_plain_double_style,
    style_for_double_position,
    style_for_existing_bond_overlay,
)

__all__ = [
    "BOLD_BOND_STYLES",
    "BOLD_DOUBLE_STYLES",
    "BOLD_DOUBLE_STYLE_SEQUENCE",
    "BOLD_STYLE_CENTER",
    "BOLD_STYLE_DEFAULT",
    "BOLD_STYLE_OUTER",
    "DEFAULT_BOLD_OUT_LENGTH_SCALE",
    "DOTTED_DOUBLE_STYLES",
    "DOTTED_DOUBLE_STYLE_DEFAULT",
    "DOTTED_DOUBLE_STYLE_OUTER",
    "DOTTED_DOUBLE_STYLE_SEQUENCE",
    "DOUBLE_STYLE_CENTER",
    "DOUBLE_STYLE_DEFAULT",
    "DOUBLE_STYLE_OUTER",
    "DOUBLE_STYLE_SEQUENCE",
    "PLAIN_DOUBLE_STYLES",
    "STANDARD_BOND_STYLES",
    "ACS1996Style",
    "LineSegment",
    "base_plain_double_style_for_dotted_variant",
    "bold_double_strip_geometry",
    "bold_double_style_for_position",
    "bold_double_style_for_style",
    "bold_out_scale",
    "cycle_plain_bond_style",
    "dotted_bond_dot_centers",
    "dotted_double_variant_for_style",
    "double_position_for_style",
    "extend_segment",
    "hash_segments_from_segment",
    "is_bold_double_bond_style",
    "is_dotted_double_bond_style",
    "is_plain_double_bond_style",
    "is_positionable_double_bond_style",
    "line_intersection",
    "normal_away_from_parallel_segment",
    "normalize_3d",
    "normalized_bold_double_style",
    "normalized_plain_double_style",
    "offset_segment",
    "plain_double_preview_segments",
    "refresh_bond_graphics",
    "scale_segment",
    "strip_corners",
    "style_for_double_position",
    "style_for_existing_bond_overlay",
    "trim_segment",
    "trimmed_line_segment",
    "wedge_triangle_from_segment",
]
