"""Bond rendering policy and Qt geometry primitives."""

from .acs1996_style import ACS1996Style, RenderMetrics
from .bond_dotted import dotted_bond_dot_centers
from .bond_geometry import (
    LineSegment,
    bold_double_strip_geometry,
    line_intersection,
    line_normal,
    normal_away_from_parallel_segment,
    normalize_3d,
    offset_segment,
    strip_corners,
    trim_segment,
)
from .bond_graphics import refresh_bond_graphics
from .bond_preview import plain_double_preview_segments
from .bond_stereo import (
    hash_segments_from_segment,
    trimmed_line_segment,
    wedge_triangle_from_segment,
)
from .bond_style import (
    BOLD_BOND_STYLES,
    BOLD_STYLE_CENTER,
    BOLD_STYLE_DEFAULT,
    BOLD_STYLE_OUTER,
    DOTTED_DOUBLE_STYLE_DEFAULT,
    DOTTED_DOUBLE_STYLE_OUTER,
    DOUBLE_STYLE_CENTER,
    DOUBLE_STYLE_DEFAULT,
    DOUBLE_STYLE_OUTER,
    PLAIN_DOUBLE_STYLES,
    STANDARD_BOND_STYLES,
    base_plain_double_style_for_dotted_variant,
    bold_double_style_for_position,
    bold_double_style_for_style,
    cycle_plain_bond_style,
    dotted_double_variant_for_style,
    double_position_for_style,
    is_bold_double_bond_style,
    is_dotted_double_bond_style,
    is_plain_double_bond_style,
    is_positionable_double_bond_style,
    normalized_bold_double_style,
    normalized_plain_double_style,
    style_for_double_position,
    style_for_existing_bond_overlay,
)
from .line_geometry import (
    ENDPOINT_SNAP_SCREEN_PX,
    LEVEL_PRESET_BOND_LENGTHS,
    LINE_ANGLE_STEP_DEGREES,
    arc_midpoint,
    arc_points,
    arrow_head_polylines,
    arrow_path_commands,
    curved_control_point,
    hex_grid_cells,
    line_click_endpoint,
    nearest_endpoint,
    new_arrow_record,
    normalized_arrow_control,
    snapped_drawing_point,
    snapped_endpoint,
    snapped_line_end,
    snapped_to_grid,
    snapped_to_hex_grid,
    wavy_line_points,
)
from .valence import ValenceWarningCache, overvalent_atom_ids

__all__ = [
    "BOLD_BOND_STYLES",
    "BOLD_STYLE_CENTER",
    "BOLD_STYLE_DEFAULT",
    "BOLD_STYLE_OUTER",
    "DOTTED_DOUBLE_STYLE_DEFAULT",
    "DOTTED_DOUBLE_STYLE_OUTER",
    "DOUBLE_STYLE_CENTER",
    "DOUBLE_STYLE_DEFAULT",
    "DOUBLE_STYLE_OUTER",
    "ENDPOINT_SNAP_SCREEN_PX",
    "LEVEL_PRESET_BOND_LENGTHS",
    "LINE_ANGLE_STEP_DEGREES",
    "PLAIN_DOUBLE_STYLES",
    "STANDARD_BOND_STYLES",
    "ACS1996Style",
    "LineSegment",
    "RenderMetrics",
    "ValenceWarningCache",
    "arc_midpoint",
    "arc_points",
    "arrow_head_polylines",
    "arrow_path_commands",
    "base_plain_double_style_for_dotted_variant",
    "bold_double_strip_geometry",
    "bold_double_style_for_position",
    "bold_double_style_for_style",
    "curved_control_point",
    "cycle_plain_bond_style",
    "dotted_bond_dot_centers",
    "dotted_double_variant_for_style",
    "double_position_for_style",
    "hash_segments_from_segment",
    "hex_grid_cells",
    "is_bold_double_bond_style",
    "is_dotted_double_bond_style",
    "is_plain_double_bond_style",
    "is_positionable_double_bond_style",
    "line_click_endpoint",
    "line_intersection",
    "line_normal",
    "nearest_endpoint",
    "new_arrow_record",
    "normal_away_from_parallel_segment",
    "normalize_3d",
    "normalized_arrow_control",
    "normalized_bold_double_style",
    "normalized_plain_double_style",
    "offset_segment",
    "overvalent_atom_ids",
    "plain_double_preview_segments",
    "refresh_bond_graphics",
    "snapped_drawing_point",
    "snapped_endpoint",
    "snapped_line_end",
    "snapped_to_grid",
    "snapped_to_hex_grid",
    "strip_corners",
    "style_for_double_position",
    "style_for_existing_bond_overlay",
    "trim_segment",
    "trimmed_line_segment",
    "wavy_line_points",
    "wedge_triangle_from_segment",
]
