"""Text and scene-annotation layout, validation, and geometry."""

from .arrow_label import (
    LABEL_SYNTAX_HINT,
    arrow_label_html,
    arrow_label_normal,
    arrow_label_position,
    cleaned_arrow_labels,
    parse_arrow_label,
)
from .brackets import (
    BRACKET_MENU_SPECS,
    DEFAULT_BRACKET_KIND,
    normalized_bracket_kind,
)
from .label_layout import (
    ATOM_LABEL_DOCUMENT_MARGIN,
    ATOM_LABEL_HIT_PADDING_RATIO,
    SUB_SCALE,
    LabelLayout,
    LabelRun,
    atom_label_presentation,
    attachment_anchor_token,
    attachment_group_at_end,
    hydride_display_text,
    hydride_hydrogen_text,
    label_bounding_rect,
    mark_dimensions,
    parse_atom_label,
    place_hydride_stack,
    place_runs,
    reversed_display_text,
    split_hydride_label,
    uses_compact_label_hit_shape,
)
from .note_html import MAX_NOTE_HTML_CHARS, sanitize_note_html
from .transforms import flip_annotation, rotate_annotation

__all__ = [
    "ATOM_LABEL_DOCUMENT_MARGIN",
    "ATOM_LABEL_HIT_PADDING_RATIO",
    "BRACKET_MENU_SPECS",
    "DEFAULT_BRACKET_KIND",
    "LABEL_SYNTAX_HINT",
    "MAX_NOTE_HTML_CHARS",
    "SUB_SCALE",
    "LabelLayout",
    "LabelRun",
    "arrow_label_html",
    "arrow_label_normal",
    "arrow_label_position",
    "atom_label_presentation",
    "attachment_anchor_token",
    "attachment_group_at_end",
    "cleaned_arrow_labels",
    "flip_annotation",
    "hydride_display_text",
    "hydride_hydrogen_text",
    "label_bounding_rect",
    "mark_dimensions",
    "normalized_bracket_kind",
    "parse_arrow_label",
    "parse_atom_label",
    "place_hydride_stack",
    "place_runs",
    "reversed_display_text",
    "rotate_annotation",
    "sanitize_note_html",
    "split_hydride_label",
    "uses_compact_label_hit_shape",
]
