"""Structure, template, and SMILES insertion planning."""

from .smiles import (
    SmilesAtomPlacement,
    SmilesBondPlacement,
    SmilesCommitPlan,
    SmilesMarkPlacement,
    annotation_mark_direction,
    annotation_mark_kinds,
    normalized_atom_annotation,
    plan_smiles_commit,
    smiles_preview_center,
    smiles_preview_offset,
)
from .structure_payload import (
    build_3d_conversion_payload,
    build_atom_annotations,
    build_structure_payload,
    build_submodel,
    expand_atom_ids_for_structure,
    model_with_atom_annotations,
)
from .template import (
    Point2D,
    TemplateInsertPlan,
    TemplateInsertRequest,
    TemplateInsertResolution,
    TemplatePointResolvers,
    normalize_template_ring_style,
    plan_template_commit,
    plan_template_preview,
    resolve_template_insert,
)
from .template_preview import (
    TemplatePreviewGeometry,
    build_benzene_template_preview_geometry,
    build_template_preview_geometry,
    plan_template_preview_update,
)

__all__ = [
    "Point2D",
    "SmilesAtomPlacement",
    "SmilesBondPlacement",
    "SmilesCommitPlan",
    "SmilesMarkPlacement",
    "TemplateInsertPlan",
    "TemplateInsertRequest",
    "TemplateInsertResolution",
    "TemplatePointResolvers",
    "TemplatePreviewGeometry",
    "annotation_mark_direction",
    "annotation_mark_kinds",
    "build_3d_conversion_payload",
    "build_atom_annotations",
    "build_benzene_template_preview_geometry",
    "build_structure_payload",
    "build_submodel",
    "build_template_preview_geometry",
    "expand_atom_ids_for_structure",
    "model_with_atom_annotations",
    "normalize_template_ring_style",
    "normalized_atom_annotation",
    "plan_smiles_commit",
    "plan_template_commit",
    "plan_template_preview",
    "plan_template_preview_update",
    "resolve_template_insert",
    "smiles_preview_center",
    "smiles_preview_offset",
]
